name: easy_sales
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter


  core:
    path: packages/core 

dependency_overrides:
  # analyzer: 8.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
   # https://pub.dev/packages/build_runner
  build_runner: ^2.10.4
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: 10.2.0 #version 10.2.1 has an issue with retrofit 4.9.1
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.11.2
  # https://pub.dev/packages/freezed
  freezed: ^3.2.3
  # https://pub.dev/packages/riverpod_generator
  riverpod_generator:  ^4.0.0+1
  # https://pub.dev/packages/riverpod_lint
  riverpod_lint: ^3.1.0
  # https://pub.dev/packages/custom_lint
  custom_lint: ^0.8.1  
  
flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    